apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - image: python:3.8
          name: fastapi-blockchain
___

apiVersion: v1
kind: Service
metadata:
  name: fastapi-blockchain
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "fastapi-blockchain"
    port: 5000
  selector:
    app: fastapi


